# Generated by Django 4.0.6 on 2022-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='submission_date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
