# Generated by Django 4.0.6 on 2022-07-28 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_attempt_submission_date_and_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='no_of_wrong_answrs',
            new_name='no_of_wrong_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField(choices=[(1, 'option 1'), (2, 'option 2'), (3, 'option 3'), (4, 'option 4')], null=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question')),
            ],
        ),
    ]
