# Generated by Django 4.0.6 on 2022-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_no_of_wrong_answrs_attempt_no_of_wrong_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
