# Generated by Django 4.0.6 on 2022-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_user_id_attempt_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highscore',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submission_date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
